### ISSUE TITLE
ANALYTICS: Opt-out Cookie

### ISSUE THREAD

**Issue by fritzmg** [friends-of-contao/contao-privacy#11]
Für einen Kunden setzen wir momentan folgendes um:

1. Es gibt einen Analytics "Opt-out" Button für alle verwendeten Analytics Scripts (der Kunde verwendet insgesamt _3_ auf seiner Seite -_-).
2. Bei Klick auf diesem Button werden per JavaScript alle Cookies der Domain gelöscht (evt. mit einer Liste an Ausnahmen) und es wird ein "Opt-out" Cookie gesetzt.
3. In allen Analytics Templates wird überprüft, ob dieses "Opt-out" Cookie gesetzt ist, wenn ja, dann wird das Analytics Script nicht ausgegeben.

Thoughts? Wäre das etwas für dieses Bundle?

**Comment by kikmedia** [comment]
Das wäre das, was man im Tagmanager voreinstellen kann? Stelle ich mir komplex vor, weil es Code auf zwei Seiten benötigt.

**Comment by joke1** [comment]
Ich fände das eine gute Alternative zum Google Tag Manager. Für letzteres benötigt man ja nur noch die Einbindung des GTM Scripts und müsste alle Contao Script Templates deaktivieren. Eine Contao Variante könnten auch Erweiterungen nutzen, was weniger Arbeit für den Nutzer bedeuten würde. Bei der Nutzung von GTM müsste ggf. auch die Datenschutzerklärung angepasst werden.

Auch im Bezug zur ePrivacy Verordnung könnte so eine Funktion dann ggf. schnell an den generischen Browser Opt-Out/Opt-In Cookie angepasst werden.

**Comment by fritzmg** [comment]
Die Lösung wäre allgemeint und unabhängig vom eingesetzten Analytics Script.

**Comment by fritzmg** [comment]
> Das wäre das, was man im Tagmanager voreinstellen kann? Stelle ich mir komplex vor, weil es Code auf zwei Seiten benötigt.

Code auf zwei Seiten? Was genau meinst du?

**Comment by fritzmg** [comment]
done
