### ISSUE TITLE
ContextErrorException im Registrierungsmodul

### ISSUE THREAD

**Issue by ben-eSM** [friends-of-contao/contao-privacy#18]
Beim Aufruf des Registrierungsmodul erhalte ich eine ContextErrorException im Debug-Modus. Import des Hängt wohl mit dem tl_member onload callback zusammen.
`Warning: in_array() expects parameter 2 to be array, null given`

Das Ganze passiert bei folgender Ausführung:
`System->import('brkwsky_privacy.listener.member_operation')`

**Comment by fritzmg** [comment]
Welche Version hast du installiert?

**Comment by ben-eSM** [comment]
Aktuell die b735554

**Comment by fritzmg** [comment]
Verwende die Releases. In Version `2.0.0-beta2` wird `brkwsky_privacy.listener.member_operation` nicht benutzt: https://github.com/friends-of-contao/contao-privacy/blob/2.0.0-beta2/src/Resources/contao/dca/tl_member.php#L14

**Comment by ben-eSM** [comment]
Ok, das erklärt es natürlich und zeigt mal wieder, dass dev-master als Versionsstring nicht unbedingt zielführend ist. ;)

**Comment by ben-eSM** [comment]
Das Problem ist, ich bin doof! Ich hab den prod cache geleert, aber nicht den dev... ;)
