### ISSUE TITLE
No BE module and extended member registration after installing

### ISSUE THREAD

**Issue by gerritlo** [friends-of-contao/contao-privacy#19]
Hey,

I installed this extension on Contao 3.5.35 via composer-client. But now I don't get any backend module and the member form wasn't changed also. Any ideas or todos after installing?

Thanks

**Comment by fritzmg** [comment]
Which version did you install?

**Comment by gerritlo** [comment]
dev-3.5-cleanup

**Comment by fritzmg** [comment]
This extension does not officially support Contao 3 yet. You have to wait for the first 1.x-beta release.

**Comment by Schmidty2** [comment]
Ich habe ebenfalls kein Modul für die erweiterte Benutzerregistrierung.
Contao 4.4.18 bei All-Inkl (Business),
Theme Rocksolid OpenSauce, 
PHP 7.1
Extension Version 0.1.1 (1.5.2018, 10:10:58) über Contao-Manager installiert
Weitere Extensions: CatalogManager, NotificationCenter (die aktuellsten Versionen)
Symfony-Caches und Systemcache gelöscht
Im Install-Tool wurde nach der Installation eine Datenbankänderung vorgenommen, keine Änderung nach Deinstallation und anschließender Neuinstallation.

**Comment by fritzmg** [comment]
> Extension Version 0.1.1 (1.5.2018, 10:10:58) über Contao-Manager installiert

Du musst Version `2.0.0-beta2` installieren.
