### ISSUE TITLE
REGISTRIERUNG: Konfigurierbare Texte

### ISSUE THREAD

**Issue by christianbarkowsky** [friends-of-contao/contao-privacy#2]
Label - sowie Infotext inkl. Link sollen konfigurierbar werden.

**Comment by frontendschlampe** [comment]
Wie besprochen wäre folgende Idee sinnvoll:

aktuell wird bei einem Standard Checkbox Input folgendes ausgegeben:
- Feldbezeichnung als ```legend``` - Eingabe: ```input.text```
- Checkbox als ```input```
- Optionen > Bezeichnung als ```label``` - Eingabe: ```input.text```

Für unsere Zwecke müsste es folgendermaßen aussehen:
- Feldbezeichnung als Überschrift in ```legend```- Eingabe: ```input.text``` mit Überschriftswähler (hier würde ich aber mal noch mit @MacKP Rücksprache halten wg. der Semantik ggfs. nur ein ```strong```)
- ausführliche Beschreibung in ```legend``` - Eingabe über TinyMCE zum Setzen von Links auf die Datenschutzvereinbarung etc.
- Checkbox bleibt wie im Standard
- Optionen > Bezeichnung bleibt wie im Standard

**Comment by christianbarkowsky** [comment]
Die Texte können wir entweder über die Root-Page einbinden - oder wir müssen ein Widget bauen. Mehr bietet die Registrierung lnicht. 🌵

**Comment by frontendschlampe** [comment]
hmmm ... es gibt auch grad Diskussionen bei Contao https://github.com/contao/core-bundle/issues/1512#issuecomment-387405474

**Comment by frontendschlampe** [comment]
Mit einem eigenen Registrierungswidget geht's nicht? Zu viel Aufwand?

**Comment by christianbarkowsky** [comment]
So wie es jetzt aufgebaut ist - nein.

**Comment by MacKP** [comment]
Wie gestern kurz mit @frontendschlampe besprochen wäre ein HTML Aufbau in der Art ganz praktisch (vereinfachte Fassung):

```
<div class="single-checkbox">
  <div class="von-contao-schon-vorhanden">
    <input>
    <label>
  </div>
  <div class="special-content">
    <h>Headline of the Content (could be used for an accordion)</h>
    <div class="special-content-content">
      Here is the Text (and a link ore something else).
    </div>
  </div>
</div>
```
Das ganze ist etwas mehr, als nur ein Link... Ich hab da eben etwas allgemeiner gedacht. Als label oder legend würde ich das nicht unterbringen, da man dort eher andere Dinge enthalten hat. Das von mir vorgeschlagene ist im Grunde eine Variante um das ganze recht einfach nutzen zu können. Um das ganze noch etwas anzureichern könnte man noch mit aria-describedby und einer ID arbeiten.

Viele Grüße

**Comment by leofeyer** [comment]
Wir müssen wohl das Frontend-Modul `ModuleRegistration` in `$GLOBALS['FE_MOD']` durch unser eigenes Modul ersetzen, damit wir das Feld hinzufügen können (siehe https://github.com/contao/core-bundle/issues/1512#issuecomment-387412382).

**Comment by frontendschlampe** [comment]
@christianbarkowsky Ich habe es gerade einmal installiert und es muss eigentlich genau andersrum sein von den Texten her.

Das "Datenschutz-Hinweis Label" (```<legend>```) muss den TinyMCE enthalten und die Beschriftung für die Checkbox "Datenschutz-Hinweis" ein einfaches Textfeld.

Es ist ja im Prinzip dann so:

Hiermit bestätigen ... Datenschutz (mit Verlinkung) ... usw.
(Checkbox) Ich stimme zu

Kannst du das kurzfristig ändern?

**Comment by frontendschlampe** [comment]
passt soweit ... muss dann nur noch in die 3.5 portiert werden
