### ISSUE TITLE
Nur als Version 0.1.1 im Contao Manager verfügbar

### ISSUE THREAD

**Issue by jhauser21** [friends-of-contao/contao-privacy#21]
Im Contao Manager ist nur die Version 0.1.1 verfügbar.
Wollte dann über die Kommandozeile die aktuelle Version installieren, bekomme dann aber die Meldung "Package friends-of-contao/contao-privacy at version 2.0.0-beta2 has a PHP requirement incompatible with your PHP version (5.6.34)" obwohl ich PHP 7.2 habe.

**Comment by frontendschlampe** [comment]
Contao 4.x? Die 2.0.0-beta2 ist nur für Contao 4

> "Package friends-of-contao/contao-privacy at version 2.0.0-beta2 has a PHP requirement incompatible with your PHP version (5.6.34)" obwohl ich PHP 7.2 habe.

dann läuft Deine Kommandozeile über PHP 5.6.34

**Comment by jhauser21** [comment]
Contao 4.4.18

**Comment by frontendschlampe** [comment]
... dann gilt mein zweiter Hinweis.

**Comment by fritzmg** [comment]
> "Package friends-of-contao/contao-privacy at version 2.0.0-beta2 has a PHP requirement incompatible with your PHP version (5.6.34)" obwohl ich PHP 7.2 habe.

Dann ist in deinem Contao Manager aber theoretisch die falsche PHP Version eingestellt. Verwendest du die neueste Version des Contao Managers?

**Comment by jhauser21** [comment]
@frontendschlampe Danke, jetzt PHP 7.2 und es funktioniert.

**Comment by rustykowski** [comment]
Ich erhalte über den Contao-Manager auch nur Version 0.1.1
Bei mir ist PHP 7.1 im Einsatz. Die Composer-Ausgabe ist lapidar:
Using version ^0.1.1 for friends-of-contao/contao-privacy
Required ist doch PHP ab 7.0?

**Comment by frontendschlampe** [comment]
Wie gesagt:

aktuell gibt es nur die Version 2.0.0-beta2 für Contao 4.x ... weitere folgen

**Comment by rustykowski** [comment]
Aber warum wird die dann nicht geladen, sondern die 0.1.1?

**Comment by rustykowski** [comment]
Danke!
