### ISSUE TITLE
Fehler beim Datenschutz-Hinweis im Registrierungsformular. Der Feldinhalt wird zum Feldnamen.

### ISSUE THREAD

**Issue by coastforge-mei** [friends-of-contao/contao-privacy#30]
Unter Contao 4.4 tritt im Registrierungsformular beim Speichern ein Fehler auf obwohl alle Felder gefüllt sind.

Der <legend> Bereich von ID ctrl_privacyConsent wird als Feldname ausgegeben.

_Die Nutzungsbedingungen sowie die Datenschutzerklärung habe ich zur Kenntnis genommen und erkläre hierzu mein Einverständnis. Die Speicherung meiner personenbezogenen Daten kann ich jederzeit per E-Mail ... widerrufen.

Bitte füllen Sie das Feld "

Die Nutzungsbedingungen sowie die Datenschutzerklärung habe ich zur Kenntnis genommen und erkläre hierzu mein Einverständnis. Die Speicherung meiner personenbezogenen Daten kann ich jederzeit per E-Mail ... widerrufen.

" aus!_

**Comment by k-webdesign** [comment]
Den Fehler kann ich leider nachvollziehen, bin auch gerade darüber gestolpert

**Comment by fritzmg** [comment]
Einverständnis zur Datenschutzerklärung soll man eh keines geben lassen ;).

Nichts desto trotz werden wir das natürlich beheben.

**Comment by christianbarkowsky** [comment]
Gucke ich mir in der nächsten Woche an.

**Comment by fritzmg** [comment]
Meiner Meinung nach sollten wir das generell umbauen.

* Es darf kein Pflichtfeld sein.
* Es darf nicht nur ein Feld sein.

Es sollte vielleicht eher als Multi Column Wizard umgesetzt werden, wo du mehrere beliebige Checkboxen definieren kannst (mit Name & Label) für die Zustimmung diverser Weiterverwendungen der Daten.

**Comment by zonky2** [comment]
ob Pflichtfeld oder nicht, würde ich dem jeweiligen Admin überlassen - das "geheule" höre ich schon jetzt ;-)

m.E. wichtiger wäre ein eigenes Widget, d.h. Text für `legend` und für Erklärungstext inkl. Links extra Ausgaben - siehe https://github.com/friends-of-contao/contao-privacy/issues/40

**Comment by fritzmg** [comment]
Ja, ich finde auch Contao braucht bei Formular Widgets generell eine Erweiterung: https://github.com/contao/contao/issues/6376

**Comment by zonky2** [comment]
> Gucke ich mir in der nächsten Woche an.

@christianbarkowsky gibt es dazu schon was Neues..?

**Comment by christianbarkowsky** [comment]
@coastforge-mei @k-webdesign @zonky2 bitte auf dem dev-master testen. Danke!

**Comment by planepix** [comment]
Danke dafür Christian. Konnte nach Update auf die dev-master nun auch die Registrierung absenden, was vorher nicht ging. Es kam immer der Hinweis, ich möge das Pflichtfeld doch anhaken.

**Comment by zonky2** [comment]
bei mir i.O. - Dank nochmal!
