### ISSUE TITLE
NEWSLETTER: IP-Adresse und Zeitpunkt der Registrierung nach X Wochen löschen

### ISSUE THREAD

**Issue by V15** [friends-of-contao/contao-privacy#31]
Zum Abonnement des Newsletters sollte ich bei einem Kunden den folgenden Text auf der Seite Datenschutz einsetzen:

> [...] Die von Ihnen eingegeben personenbezogenen Daten werden solange gespeichert, bis Ihr Abonnement bei uns gekündigt wird. IP-Adresse und Zeitpunkt der Registrierung werden für die Dauer von XXX [Zulässige Dauer der Speicherung: 2-4 Wochen] Wochen gespeichert. [...]

Daher müste auch hier sichergestellt werden, das diese Daten automatisch nach einem Zeitraum von X Wochen gelöscht werden.

**Comment by leofeyer** [comment]
Das ist aber nicht korrekt, oder?

Die IP-Adresse darf man genauso lange speichern wie auch die E-Mail-Adresse – in diesem Fall für die komplette Zeit des Abonnements. Wie weist man sonst nach 6 Monaten das Double Opt-In nach?

Sämtliche für das Abonnement benötigten Daten (Sichtwort: Datensparsamkeit) sollte man bis zur Kündigung speichern und nicht Teile davon nach 4 Wochen vernichten. Dazu gibt es keinen Grund.

**Comment by V15** [comment]
Klingt nachvollziehbar und sinnvoll.
