### ISSUE TITLE
Backport der Contao 4.6-Änderungen?

### ISSUE THREAD

**Issue by leofeyer** [friends-of-contao/contao-privacy#33]
Ich habe [hier](https://github.com/contao/core-bundle/issues/1512#issuecomment-401007331) zusammengefasst, was wir für Contao 4.6 im Hinblick auf die DSGVO angepasst haben. Eventuell sollten wir diese Änderungen in das Bundle übernehmen?

Was ist eigentlich mit den ganzen bereits implementierten Features, die sich im Nachhinein als unnötig herausgestellt haben? Entfernen wie die wieder?

**Comment by frontendschlampe** [comment]
> Ich habe hier zusammengefasst, was wir für Contao 4.6 im Hinblick auf die DSGVO angepasst haben. Eventuell sollten wir diese Änderungen in das Bundle übernehmen?

Yep ... sollten wir irgendwie übernehmen

> Was ist eigentlich mit den ganzen bereits implementierten Features, die sich im Nachhinein als unnötig herausgestellt haben? Entfernen wie die wieder?

Würde ich nicht entfernen. Es sind ja eigentlich immer zusätzliche Module/Contentelemente und ich habe es bei mehreren Kunden versucht, sie davon zu überzeugen, dass es nicht nötig ist, z.B. bei Kommentaren eine Checkbox zu haben, aber da führt einfach kein Weg dran vorbei. Da deren Anwalt es so möchte, muss es entsprechend gemacht werden. Die Features sind ja nun einmal eingearbeitet.

**Comment by leofeyer** [comment]
Ja, das ist verständlich. Dann lassen wir sie natürlich drin.

**Comment by Paddy0174** [comment]
Gibt es hierzu schon eine Entscheidung?

Ich wäre sehr für einen Backport der Änderungen! Ich würde nur ungern meine LTS-Versionen, die ja erst in der letzten Zeit von 3.5 geupdated wurden, nun auf die normalen Versionen hoch ziehen. Da argumentiere ich beim Kunden genau ins Gegenteil...
