### ISSUE TITLE
Can´t install

### ISSUE THREAD

**Issue by Sizoberz** [friends-of-contao/contao-privacy#35]
Contao Version 4.5.10
Error message
$ /usr/bin/php7.2-cli '-q' '-d' 'memory_limit=-1' '/XXX/web/contao-manager.phar.php' 'composer' 'require' 'friends-of-contao/contao-privacy' '--no-progress' '--no-suggest' '--no-update' '--no-scripts' '--prefer-stable' '--sort-packages' '--no-ansi' '--no-interaction' 2>&1

In InitCommand.php line 718:
                                                                               
  Could not find a version of package friends-of-contao/contao-privacy matchi  
  ng your minimum-stability (stable). Require it with an explicit version con  
  straint allowing its desired stability.                                      
                                                                               

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

# Process terminated with exit code 1
# Result: General error``

**Comment by fritzmg** [comment]
Use
```
composer require 'friends-of-contao/contao-privacy:^2.0@beta
```

**Comment by Sizoberz** [comment]
Thank you @fritzmg. the installation work, but I get an error that I have to fill out the privacy field, although I check the box. Also I guess the confirmation email won´t work because it only work with the notification module in my installation with the regular registration module from contao.

**Comment by fritzmg** [comment]
No I meant, what module are you talking about exactly? Registration module?

**Comment by Sizoberz** [comment]
The new availabe "Registrierung (DSGVO)" module

**Comment by Sizoberz** [comment]
![grafik](https://user-images.githubusercontent.com/34723382/43046754-f16d1082-8dcd-11e8-9a35-8019f0a0ea01.png)

**Comment by Sizoberz** [comment]
but it was checked when I send form

**Comment by fritzmg** [comment]
You do not need such a Checkbox anyway ;). It's even inadvisable to do that.

Listen to this podcast: https://www.datenschutz-guru.de/braucht-mein-kontaktformular-jetzt-eine-checkbox/

**Comment by Sizoberz** [comment]
? ok but for what I need the privacy module then - what is the difference?
I also se that the check box is also availabe in the regular form since the module installation - I´m a bit confused - can we chat in german?

**Comment by Sizoberz** [comment]
When I use the regular for with the privacy checkbox activated it work.
Only bad thing is in the regular form I can´t set the privacy hint and label text, that it looks like that:
![grafik](https://user-images.githubusercontent.com/34723382/43049174-5d7fd726-8df3-11e8-832c-409b632e5b0e.png)
With the DSGVO form I get the mentioned error.
Is there a way to bring the hint and label fields in the regular form, too?

**Comment by fritzmg** [comment]
> ? ok but for what I need the privacy module then - what is the difference?

If you sell your user's data to spammers for example, you need to get the consent of the user to optionally allow that for example.

However, the checkbox is currently mandatory - so we should probably change that as well.

**Comment by zonky2** [comment]
> Use
> `composer require friends-of-contao/contao-privacy:^2.0@beta`

it is currently not possible to install the extension "just like that" via the Contao manager - there is an error message that says little (but it is rather a matter of the manager)

I already had two agencies that I implanted via the console - my advertising for a donation to the project hasn't been that successful so far...

**Comment by fritzmg** [comment]
It is perfectly possible to install this extension via the Contao Manager. You simply have to set the requirement to `^2.0@beta` manually.

**Comment by fritzmg** [comment]
;) https://youtu.be/AeXhw7K2hw0

**Comment by zonky2** [comment]
great - you could write "currently in manager `^2.0@beta`" in the readme, until stable version
