### ISSUE TITLE
Youtube - Caption für Splash Image

### ISSUE THREAD

**Issue by operatorone** [friends-of-contao/contao-privacy#38]
Kleiner Verbesserungswunsch: 

Im Backend wäre es super, wenn noch das Feld Bildunterschrift (caption) vorhanden wäre um einen Hinweis zum Splash Image platzieren zu können, wie z. B. **Bild anklicken um Video zu starten.**

**Comment by fritzmg** [comment]
Das müsstest du ja dann bei jedem Bild eingeben. Wäre CSS nicht besser geeignet für diesen Fall?

**Comment by operatorone** [comment]
Die Bildunterschrift müsste ja kein Pflichtfeld sein, sondern nur optional. 

Was meintest du mit 
> Wäre CSS nicht besser geeignet für diesen Fall?

**Comment by fritzmg** [comment]
Mit einem :after Pseudoselektor bspw.

Semantisch wäre aber eine Template Anpassung besser. Dann ersparst du dir auch die Eingabe im Backend.

**Comment by operatorone** [comment]
Ach so, ja das wäre eine Möglichkeit. Wenn man natürlich einen Template-Eintrag hätte, könnte man den auch gleich mehrsprachig hinterlegen und falls nicht gewollt einfach per CSS ausblenden.
