### ISSUE TITLE
Difference between heimrichhannot and friends-of-contao?

### ISSUE THREAD

**Issue by Aybee** [friends-of-contao/contao-privacy#39]
Hallo, wenn ich in den Paketen nach "privacy" suche, dann bekomme ich diese Erweiterung und diese hier angeboten https://github.com/heimrichhannot/contao-privacy

Was ist denn da der Unterschied, bzw. welche soll man da nehmen? Es wird ja immer mal wieder von der Erweiterung "contao-privacy" gesprochen, welche ist damit gemeint?

**Comment by fritzmg** [comment]
Soweit ich das sehe hat diese Extension nichts mit foc/contao-privacy zu tun. Heißt wohl nur zufällig genau so. Genaueres kann dir sicher @heimrichhannot sagen ;)

**Comment by Aybee** [comment]
Ok, danke, dann werde ich ihn dort mal fragen.

**Comment by frontendschlampe** [comment]
@Aybee wenn im Allgemeinen die Rede von "contao-privacy" ist, sollte es sich um dieses Paket hier drehen. ;-)

**Comment by Aybee** [comment]
Ok, danke dir.
