### ISSUE TITLE
MITGLIEDERREGISTRIERUNG: FE: Checkbox meldet immer Fehler auch wenn angeklickt

### ISSUE THREAD

**Issue by zonky2** [friends-of-contao/contao-privacy#40]
Checkbox meldet immer Fehler auch wenn angeklickt - im BE gibt es da ja nicht viel einzustellen...

![screenshot_219](https://user-images.githubusercontent.com/1045318/45167837-45747300-b1fa-11e8-822d-54bd0172b381.jpg)

Zusatzfrage: der Text "Datenschutz-Hinweis" wird in die Legend geschrieben inkl. dem `<p>` Tag, den Tiny immer hinzu fügt... kann man den abschalten?

Bei der Fehlermeldung wird dann der Text im `<p>` der Errormeldung inkl. `<p>` wieder eingefügt - deshalb sieht die Meldung so Grütze aus...

Wäre es nicht besser ein Feld für Legend zu vergeben und den Hinweistext als eigenständigen HTML-Block auszugeben? Leider kann ich hier für das Checkbox-Widget kein eigenes Template anwählen.

Edit: wenn ich https://wiki.selfhtml.org/wiki/Referenz:HTML/legend richtig interpretiere, ist ein `<p>` im `<legend>` nicht erlaubt...

**Comment by fritzmg** [comment]
Ja, der Text darf nicht über einen TinyMCE eingegeben werden, das sollten wir fixen.

Davon abgesehen solltest du Datenschutzbestimmungen nicht akzeptieren lassen: https://www.datenschutz-guru.de/braucht-mein-kontaktformular-jetzt-eine-checkbox/

**Comment by zonky2** [comment]
Ohne Tiny wird es schwierig die Links ohne Inserttags einzusetzen...

hier geht es ja nicht um ein normales Kontaktformular, sondern um eine Anmeldung/Registrierung - die Entscheidung sollte den "Kunden"/Contao-Nutzer überlassen werden

wenn es für das Registierungsforrmular eine Checkbox gibt, sollte die auch funktionieren

**Comment by fritzmg** [comment]
> Ohne Tiny wird es schwierig die Links ohne Inserttags einzusetzen...

Bei regulären Checkboxen im Formulargenerator hast du auch keine andere Wahl.

> hier geht es ja nicht um ein normales Kontaktformular, sondern um eine Anmeldung/Registrierung

Das spielt keine Rolle. Auch hier musst du nicht einer Datenschutzbestimmung zustimmen lassen. Solltest du auch nicht. Wenn überhaupt brauchst du optionale Zustimmungen, wenn du die eingegebenen Daten anderweitig verwenden willst.

> die Entscheidung sollte den "Kunden"/Contao-Nutzer überlassen werden

Ja, wie @frontendschlampe schon in einem anderen Ticket erwähnt hat, liegt das Problem ja meist beim Kunden oder dessen Anwalt, die Dinge umgesetzt haben wollen, die vielleicht nicht notwendig oder gar unsinnig sind.

> wenn es für das Registierungsforrmular eine Checkbox gibt, sollte die auch funktionieren

Natürlich, darum habe ich ja gesagt, dass wir das fixen müssen ;)

**Comment by zonky2** [comment]
o.k.

**Comment by zonky2** [comment]
selber Fehler wie hier: https://github.com/friends-of-contao/contao-privacy/issues/30

sorry, hatte ich nicht gesehen...
