### ISSUE TITLE
Kein Splashscreen

### ISSUE THREAD

**Issue by planepix** [friends-of-contao/contao-privacy#42]
Hallo zusammen,

eine Contao 4.4.26 mit dem Bundle 2.0.0-beta6 und einem Video eingebunden.

Eine Datei als Splashscreen ist angegeben.
Diese Grafik - ob JPG oder PNG - wird aber nicht angezeigt. Auch im Quellcode ist kein Hinweis darauf zu finden.
Ist sonst noch etwas zu berücksichtigen oder ist das ein Bug?

Danke und Grüße
Thomas

**Comment by planepix** [comment]
Es war gleichzeitig wohl noch die Erweiterung youtube-iframe installiert.

**Comment by Aybee** [comment]
Ah, muss man youtube-iframe deinstallieren, wenn man contao-privacy installiert? Ich stelle nämlich auch gerade fest, dass bei mir mit beiden Erweiterungen das Template ce_youtube von contao-privacy nicht benutzt wird.

**Comment by fritzmg** [comment]
Ja, wenn mehrere Erweiterungen das selbe Template überschreiben, kann natürlich nur eine Erweiterung gewinnen.

**Comment by Aybee** [comment]
Zum Thema:
https://github.com/friends-of-contao/contao-privacy/issues/47
https://github.com/fritzmg/contao-youtube-iframe/issues/9
