### ISSUE TITLE
YOUTUBE: Einarbeitung 2-Click-Variante

### ISSUE THREAD

**Issue by frontendschlampe** [friends-of-contao/contao-privacy#8]
Eine Überlegung gibt es, dass ein YouTube-Video beim ersten Seitenaufruf noch nicht geladen wird, sondern nur das Vorschaubild und ein Hinweistext. Laut meinen Informationen hat @aschempp sowas schon mal irgendwo verbaut. Ggfs. kann er uns dazu den Code zur Verfügung stellen.

**Comment by leofeyer** [comment]
Das wäre doch egal, wenn wir nocookie einbauen, oder?

**Comment by frontendschlampe** [comment]
naja, nocookie bedeutet ja nur, dass keine Cookies gesetzt werden, aber es bedeutet nicht, dass keine persönlichen Informationen (z.B. IP-Adresse) übertragen werden.

**Comment by fritzmg** [comment]
done

**Comment by Aybee** [comment]
> @frontendschlampe  nur das Vorschaubild und ein Hinweistext

Ein Hinweistext fehlt leider noch. Da der Klick auf das Vorschaubild Verbindungen zu YouTube aufbaut, dürfte ein Vorschaubild ohne Hinweis in Textformat nicht ausreichen. Sollte so in etwa sein, wie bei dlh_googlemaps. Ein standard Hinweistext, welchen man noch überschreiben kann.

**Comment by fritzmg** [comment]
Wie andernorts besprochen sollte man das eher über eine Template Anpassung individuell lösen.
