### ISSUE TITLE
Anpassung der composer.json

### ISSUE THREAD

**Issue by leofeyer** [friends-of-contao/contao-privacy#9]
Der Namespace in der `composer.json` lautet noch `christianbarkowsky` bzw. `Brkwsky\\`.

Außerdem sollten wir `"contao/core-bundle": "4.4* || 4.5.*"` requiren, weil die Privacy-Änderungen ja in Contao 4.6 im Core enthalten sein werden.

**Comment by frontendschlampe** [comment]
Der Namespace sollte mittlerweile angepasst sein.

Was die Beschränkung auf 4.4 und 4.5 angeht, da müssten wir nochmal schauen, ob du alles in den Core übernehmen möchtest. @MDevster hat die Idee mit dem Infoscreen umgesetzt, die in unseren Augen sehr sinnvoll ist. Die Frage ist nun aber, ob du das auch mit in den Core übernimmst! Wir können dazu gern nochmal sprechen.

**Comment by leofeyer** [comment]
Lass uns das mal heute beim Call besprechen.

**Comment by leofeyer** [comment]
Wie am 17. Mai auf Mumble besprochen, sollte das Bundle in der Art eines Polyfills aufgebaut sein, das Features nur hinzufügt, wenn der Core sie nicht hat. Dazu muss z.B. die Existenz des Bestätigungsfeldes bei der Registrierung oder des YouTube-Optionsfeldes geprüft werden.
